

# CLI OLLAMA

from langchain_ollama import OllamaLLM
from langchain.prompts import PromptTemplate


template = """
You are a summarization AI. Please summarize the following text:

{text}


Please wait... Your Summary is loading...
"""

model = OllamaLLM(model="llama3")
prompt = PromptTemplate.from_template(template)

def preprocess_text(text):
    return ' '.join(text.split())

def summarize_text():
    print('\n')
    print("Welcome to the Text Summarizer!")
    print("To summarize an article, paste your text and type 'exit' on a new line.")
    print("To completely stop the program, type 'quit'.")

    while True:
        long_text = []
        while True:
            line = input()

            if line.lower() == 'exit':
                if long_text:
                    full_text = '\n'.join(long_text)
                    break
                else:
                    print("Error: No text entered. Please enter some text to summarize.")
                    continue

            if line.lower() == 'quit':
                print("\nThanks for using this Summarizer. Exiting...")
                return
            
            long_text.append(line)

        processed_text = preprocess_text(full_text)

        print(f"\nInput Text:\n{processed_text}\n")

        formatted_prompt = prompt.format(text=processed_text)

        print(f"\nFormatted Prompt:\n{formatted_prompt}\n")
        
        try:
            result = model(formatted_prompt)
            print("\nSummary generated by model:\n", result)
        
        except Exception as e:
            print(f"Error occurred while generating summary: {e}")

        print("\nTo summarize an article, paste your text and type 'exit' on a new line.")
        print("To completely stop the program, type 'quit'.")


summarize_text()

# Use the below line in cmd terminal
# .\chatbot\Scripts\activate.bat
# After running the below line in terminal, run the code with, py main.py
