import os
from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq


template = """
You are a summarization AI. Please summarize the following text:

{text}


Please wait... Your Summary is loading...
"""

model = ChatGroq(temperature=0,
               groq_api_key=os.getenv('GROQ_API_KEY'),
               model_name=os.getenv('GROQ_MODEL', 'llama-3.1-70b-versatile')
               )
prompt = ChatPromptTemplate.from_template(template)
chain = prompt | model

def preprocess_text(text):
    return ' '.join(text.split())

def summarize_text():
    print('\n')
    print("Welcome to the Text Summarizer!")
    print("To summarize an article, paste your text and type 'exit' on a new line.")
    print("To completely stop the program, type 'quit'.")

    while True:
        long_text = []
        while True:
            line = input()

            if line.lower() == 'exit':
                if long_text:
                    full_text = '\n'.join(long_text)
                    break
                else:
                    print("Error: No text entered. Please enter some text to summarize.")
                    continue

            if line.lower() == 'quit':
                print("\nThanks for using this Summarizer. Exiting...")
                return
            
            long_text.append(line)

        processed_text = preprocess_text(full_text)

        print(f"\nInput Text:\n{processed_text}\n")

        formatted_prompt = prompt.format(text=processed_text)

        print(f"\nFormatted Prompt:\n{formatted_prompt}\n")
        
        try:
            result = chain.invoke({"text" :formatted_prompt})
            answer = result.content
            print("\nSummary generated by model:\n", answer)
        
        except Exception as e:
            print(f"Error occurred while generating summary: {e}")

        print("\nTo summarize an article, paste your text and type 'exit' on a new line.")
        print("To completely stop the program, type 'quit'.")


summarize_text()