name: Deploy Text Summarizer (Docker CI/CD)

on:
  push:
    branches:
      - main

jobs:

  # -------------------------
  # BUILD + PUSH IMAGE
  # -------------------------
  build-and-push:
    name: Build & Push Docker Image
    runs-on: [self-hosted, ts]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          export DOCKER_BUILDKIT=1

          echo "🏗️ Building image (with BuildKit)"
          docker build \
            -t krish1908/text-summarizer:v${{ github.run_number }} \
            .

          echo "📤 Pushing image"
          docker push krish1908/text-summarizer:v${{ github.run_number }}

  # # -------------------------
  # # DEPLOY TO AWS
  # # -------------------------
  # deploy-aws:
  #   name: Deploy to AWS
  #   runs-on: [self-hosted, ts, aws]
  #   needs: build-and-push

  #   steps:
  #     - name: Deploy via Docker (AWS)
  #       run: |
  #         echo "🚀 Deploying to AWS..."

  #         echo "📥 Pull versioned image"
  #         docker pull krish1908/text-summarizer:v${{ github.run_number }}
  #         echo "✅ Pulled versioned image"

  #         echo "🛑 Stop old container"
  #         docker stop text-summarizer-container || true
  #         echo "🛑 Stopped old container"

  #         echo "🗑 Remove old container"
  #         docker rm text-summarizer-container || true
  #         echo "🗑 Removed old container"

  #         echo "🚀 Run new container"
  #         docker run -d \
  #           -p 127.0.0.1:8021:8000 \
  #           --name text-summarizer-container \
  #           --restart always \
  #           --env-file /var/www/Text_Summarizer/.env \
  #           krish1908/text-summarizer:v${{ github.run_number }}
  #         echo "🚀 Running new container"

  #         echo "🔄 Reload services"
  #         sudo systemctl reload nginx
  #         sudo systemctl daemon-reload
  #         echo "✅ AWS Deployment Done"


  # -------------------------
  # DEPLOY TO ON-PREM
  # -------------------------
  deploy-onprem:
    name: Deploy to On-Prem
    runs-on: [self-hosted, ts, on-prem]
    needs: build-and-push

    steps:
      - name: Deploy via Docker (On-Prem)
        run: |
          echo "🚀 Deploying to On-Prem..."

          echo "📥 Pull versioned image"
          docker pull krish1908/text-summarizer:v${{ github.run_number }}
          echo "✅ Pulled versioned image"

          echo "🛑 Stop old container"
          docker stop text-summarizer-container || true
          echo "🛑 Stopped old container"

          echo "🗑 Remove old container"
          docker rm text-summarizer-container || true
          echo "🗑 Removed old container"

          echo "🚀 Run new container"
          docker run -d \
            -p 127.0.0.1:8021:8000 \
            --name text-summarizer-container \
            --restart always \
            --env-file /data/Text_Summarizer/.env \
            --memory="512m" \
            --cpus="1.0" \
            --log-opt max-size=10m \
            --log-opt max-file=3 \
            krish1908/text-summarizer:v${{ github.run_number }}

          echo "⏳ Waiting for container..."
          sleep 5

          echo "🧪 Health check"
          curl -f http://127.0.0.1:8021 || exit 1

          echo "🔄 Reload nginx"
          sudo systemctl reload nginx

          echo "✅ On-Prem Deployment Done"

  # -------------------------
  # DEPLOY TO KM GCP
  # -------------------------
  deploy-km-gcp:
    name: Deploy to KM GCP
    runs-on: [self-hosted, ts, gcp, km]
    needs: build-and-push

    steps:
      - name: Deploy via Docker (KM GCP)
        run: |
          echo "🚀 Deploying to KM GCP..."

          echo "📥 Pull versioned image"
          docker pull krish1908/text-summarizer:v${{ github.run_number }}
          echo "✅ Pulled versioned image"

          echo "🛑 Stop old container"
          docker stop text-summarizer-km || true
          echo "🛑 Stopped old container"

          echo "🗑 Remove old container"
          docker rm text-summarizer-km || true
          echo "🗑 Removed old container"

          echo "🚀 Run new container"
          docker run -d \
            -p 127.0.0.1:8021:8000 \
            --name text-summarizer-km \
            --restart always \
            --env-file /var/krish/.env \
            -e OTEL_SERVICE_NAME=text-summarizer \
            -e OTEL_TRACES_EXPORTER=otlp \
            -e OTEL_METRICS_EXPORTER=none \
            -e OTEL_LOGS_EXPORTER=none \
            -e OTEL_EXPORTER_OTLP_ENDPOINT=172.17.0.1:4317 \
            -e OTEL_EXPORTER_OTLP_PROTOCOL=grpc \
            -e OTEL_RESOURCE_ATTRIBUTES=deployment.environment=dev \
            --memory="512m" \
            --cpus="1.0" \
            --log-opt max-size=10m \
            --log-opt max-file=3 \
            krish1908/text-summarizer:v${{ github.run_number }}

          echo "⏳ Waiting for container..."
          sleep 5

          echo "🧪 Health check"
          curl -f http://127.0.0.1:8021 || exit 1

          echo "✅ KM GCP Deployment Done"