name: Deploy Text Summarizer (Docker CI/CD)

on:
  push:
    branches:
      - main

jobs:

  # -------------------------
  # BUILD + PUSH IMAGE
  # -------------------------
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images (latest + version)
        run: |
          docker build -t krish1908/text-summarizer:latest .
          docker build -t krish1908/text-summarizer:v${{ github.run_number }} .

      - name: Push Docker Images
        run: |
          docker push krish1908/text-summarizer:latest
          docker push krish1908/text-summarizer:v${{ github.run_number }}


  # # -------------------------
  # # DEPLOY TO AWS
  # # -------------------------
  # deploy-aws:
  #   name: Deploy to AWS
  #   runs-on: [self-hosted, ts, aws]
  #   needs: build-and-push

  #   steps:
  #     - name: Deploy via Docker (AWS)
  #       run: |
  #         echo "🚀 Deploying to AWS..."

  #         echo "📥 Pull versioned image"
  #         docker pull krish1908/text-summarizer:v${{ github.run_number }}

  #         echo "🛑 Stop old container"
  #         docker stop text-summarizer-container || true

  #         echo "🗑 Remove old container"
  #         docker rm text-summarizer-container || true

  #         echo "🚀 Run new container"
  #         docker run -d \
  #           -p 127.0.0.1:8021:8000 \
  #           --name text-summarizer-container \
  #           --restart always \
  #           krish1908/text-summarizer:v${{ github.run_number }}

  #         echo "🔄 Reload services"
  #         sudo systemctl reload nginx
  #         sudo systemctl daemon-reload
  #         echo "✅ AWS Deployment Done"


  # -------------------------
  # DEPLOY TO ON-PREM
  # -------------------------
  deploy-onprem:
    name: Deploy to On-Prem
    runs-on: [self-hosted, ts, on-prem]
    needs: build-and-push

    steps:
      - name: Deploy via Docker (On-Prem)
        run: |
          echo "🚀 Deploying to On-Prem..."

          echo "📥 Pull versioned image"
          docker pull krish1908/text-summarizer:v${{ github.run_number }}

          echo "🛑 Stop old container"
          docker stop text-summarizer-container || true

          echo "🗑 Remove old container"
          docker rm text-summarizer-container || true

          echo "🚀 Run new container"
          docker run -d \
            -p 127.0.0.1:8021:8000 \
            --name text-summarizer-container \
            --restart always \
            krish1908/text-summarizer:v${{ github.run_number }}

          echo "🔄 Reload services"
          sudo systemctl reload nginx
          sudo systemctl daemon-reload
          echo "✅ On-Prem Deployment Done"